spring.application.name=manager

# Activa el perfil prod en Render si la variable existe; si no, usa el default en local
spring.profiles.active=${SPRING_PROFILES_ACTIVE:default}

# Render usa PORT, Docker suele usar 8080 o 8000. Esto cubre ambos:
server.port=${PORT:8080}

# Conexión a MongoDB
spring.data.mongodb.uri=${MONGODB_URI}

# Evita que el driver de MongoDB bloquee el arranque si la conexión tarda en responder las réplicas
spring.data.mongodb.auto-index-creation=false

# Forzamos a Spring a que use tu SecurityConfig y no la de autogeneración
spring.main.allow-bean-definition-overriding=true

# Evita que Spring intente configurar un UserDetailService por su cuenta
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

# ID de tu proyecto en Google Cloud
spring.cloud.gcp.project-id=${ANALOG_CAMPUS_PROJECT_ID}

# Configuración del Microservicio de PDFs
cloud.service.pdf.url=https://generate-contacts-pdf-808325499853.us-west1.run.app

# Permite que la aplicación responda al puerto antes de terminar de procesar todo de forma síncrona
spring.main.lazy-initialization=true