spring.application.name=manager

# Render usa PORT, Docker suele usar 8080 o 8000. Esto cubre ambos:
server.port=${PORT:8080}

# Conexión a MongoDB
spring.data.mongodb.uri=${MONGODB_URI}

# Forzamos a Spring a que use tu SecurityConfig y no la de autogeneración
spring.main.allow-bean-definition-overriding=true

# Evita que Spring intente configurar un UserDetailService por su cuenta
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

# ID de tu proyecto en Google Cloud
spring.cloud.gcp.project-id=${ANALOG_CAMPUS_PROJECT_ID}

# Ruta absoluta al archivo JSON descargado
spring.cloud.gcp.credentials.location=file:${ANALOG_CAMPUS_CREDENTIALS_PATH}

# Configuración del Microservicio de PDFs
cloud.service.pdf.url=https://generate-contacts-pdf-808325499853.us-west1.run.app
