spring.application.name=manager

# Render usa PORT, Docker suele usar 8080 o 8000. Esto cubre ambos:
server.port=${PORT:8080}

# Conexión a MongoDB
spring.data.mongodb.uri=${MONGODB_URI}

# Forzamos a Spring a que use tu SecurityConfig y no la de autogeneración
spring.main.allow-bean-definition-overriding=true

# Evita que Spring intente configurar un UserDetailService por su cuenta
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
